@StoreAPI_HostAddress = http://localhost:5283

@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4wMSIsImp0aSI6IjNjOTY4ZDM5LTFhYmQtNDIzNi1hZjJmLTNmMmIyYzE4ZTgxOSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzQwNjY3ODMzLCJpc3MiOiIqIiwiYXVkIjoiKiJ9.i-YuJSDM6w_A7Txq4ETlBpeqTE6tk-Nj2gwIWyNXd1k

// check db connect
GET {{StoreAPI_HostAddress}}/api/Product/test-db
Accept: application/json

###
GET {{StoreAPI_HostAddress}}/api/Product
Accept: application/json
Authorization: Bearer {{Token}}

###
GET {{StoreAPI_HostAddress}}/api/Product/8
Accept: application/json
Authorization: Bearer {{Token}}


###
POST {{StoreAPI_HostAddress}}/api/Product
Accept: application/json
Content-Type: application/json

{
  "category_id": 2,
  "product_name": "iPad Pro 15 Pro Max",
  "unit_price":122000,
  "product_picture": "https://www.mxphone.com/wp-content/uploads/2021/04/41117-79579-210401-iPhone12ProMax-xl-1200x675.jpg",
  "unit_in_stock": 112,
  "created_date": "2021-11-22T00:00:00",
  "modified_date": "2021-11-22T00:00:00"
}

###
PUT {{StoreAPI_HostAddress}}/api/Product/1
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "category_id": 2,
  "product_name": "iPad Pro 17 Pro Max",
  "unit_price":122000,
  "product_picture": "https://www.mxphone.com/wp-content/uploads/2021/04/41117-79579-210401-iPhone12ProMax-xl-1200x675.jpg",
  "unit_in_stock": 112,
  "created_date": "2021-11-22T00:00:00",
  "modified_date": "2021-11-22T00:00:00"
}

###
DELETE  {{StoreAPI_HostAddress}}/api/Product/1
Accept: application/json

